### ISSUE TITLE
página inicial do sistema #7

### ISSUE THREAD

**Issue by amandagabriela74** [i4n-v/booked#8]
**Como** desenvolvedor;
**Quero** implementar a página inicial do meu sistema;
**Para** apresentar aos meus usuários;

- [ ] implementar uma funcionalidade de pesquisa para que os usuários possam encontrar facilmente o conteúdo que desejam no meu aplicativo;
- [x] Implementar um carrossel destacando os principais livros do sistema;
- [x] Identificar os elementos da interface do sistema que se repetem e criar componentes.

**Critérios de aceitação:**
- Deve haver um menu de navegação para as diferentes seções do sistema;
- Se o usuário não estiver logado, deve mostrar o botão para criar uma conta ou fazer login;
- A página deve ser visualmente atraente e coerente com a identidade visual do sistema.

**Comment by i4n-v** [comment]
Finalizada, porém sem a pesquisa dos livros.
